blueprint:
  homeassistant:
    min_version: 2024.12.0
  author: Citrowallon
  domain: automation
  name: IKEA Shortcut Button (E1812) Control
  description: "## Control anything with **Shortcut Button (E1812)** remote\n\nOnly for use with Zigbee2MQTT ##"
  input:
    button:
      name: Remote
      description: 'IKEA remote (Somrig, Rodret) to use.'
      default: []
      selector:
        device:
          filter:
          - integration: mqtt
            manufacturer: IKEA
            model: TRADFRI shortcut button (E1812)
          multiple: false
    button_1_single:
      name: Action when 1_short_release sended
      description: Action to run when SHORT press on button 1
      default: []
      selector:
        action: {}
    button_1_double:
      name: Action when 1_double_press sended
      description: Action to run when DOUBLE SHORT press on button 1
      default: []
      selector:
        action: {}
    button_1_long:
      name: Action when 1_long_press sended
      description: Action to run when LONG press on button 1
      default: []
      selector:
        action: {}
    button_2_single:
      name: Action when 2_short_release sended
      description: Action to run when SHORT press on button 2
      default: []
      selector:
        action: {}
    button_2_double:
      name: Action when 2_double_press sended
      description: Action to run when DOUBLE SHORT press on button 2
      default: []
      selector:
        action: {}
    button_2_long:
      name: Action when 2_long_press sended
      description: Action to run when LONG press on button 2
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: state
  entity_id:
  - !input button
  to: 1_short_release
  id: 1_short_release
- platform: state
  entity_id:
  - !input button
  to: 1_double_press
  id: 1_double_press
- platform: state
  entity_id:
  - !input button
  to: 1_long_press
  id: 1_long_press
- platform: state
  entity_id:
  - !input button
  to: 2_short_release
  id: 2_short_release
- platform: state
  entity_id:
  - !input button
  to: 2_double_press
  id: 2_double_press
- platform: state
  entity_id:
  - !input button
  to: 2_long_press
  id: 2_long_press
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id: 1_short_release
    sequence: !input button_1_single
  - conditions:
    - condition: trigger
      id: 1_double_press
    sequence: !input button_1_double
  - conditions:
    - condition: trigger
      id: 1_long_press
    sequence: !input button_1_long
  - conditions:
    - condition: trigger
      id: 2_short_release
    sequence: !input button_2_single
  - conditions:
    - condition: trigger
      id: 2_double_press
    sequence: !input button_2_double
  - conditions:
    - condition: trigger
      id: 2_long_press
    sequence: !input button_2_long
