blueprint:
  name: Z2M IKEA Shortcut Button E1812 
  description: "Blueprint for Ikea Tradfri Shortcut Button E1812. You can put several
    actions to each single press, double press and long press. \nImprovement of the original blueprint to avoid *_action entities usage"
  domain: automation
  source_url: https://github.com/Citrowallon/blueprints-HA/blob/main/e1812.yaml
  input:
    button:
      name: Remote
      description: IKEA Shortcut Button to use (e.g sensor.kitchen_remote_action)
      selector:
        device:
          filter:
          - integration: mqtt
            manufacturer: IKEA
            model: TRADFRI shortcut button (E1812)
          multiple: false
    base_topic:
      name: (Zigbee2MQTT) Base mqtt topic
      description: The topic configured in [Z2M addon](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html).
      default: zigbee2mqtt
    single:
      name: Action when On sended
      description: Action to run when SHORT press
      default: []
      selector:
        action: {}
    double:
      name: Action when Off sended
      description: Action to run when DOUBLE SHORT press
      default: []
      selector:
        action: {}
    long:
      name: Action when Brightness_move_up sended
      description: Action to run when LONG press
      default: []
      selector:
        action: {}
    released:
      name: Action when Brightness_stop sended
      description: Action to run when LONG press RELEASED
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger_variables:
  z2m_base_topic: !input base_topic
  z2m_controller: !input button
trigger:
- platform: mqtt
  topic: '{{ z2m_base_topic ~ ''/'' ~ z2m_controller ~ ''/action'' }}'
  payload: 'off'
  id: 'off'
- platform: mqtt
  topic: '{{ z2m_base_topic ~ ''/'' ~ z2m_controller ~ ''/action'' }}'
  payload: 'on'
  id: 'on'
- platform: mqtt
  topic: '{{ z2m_base_topic ~ ''/'' ~ z2m_controller ~ ''/action'' }}'
  payload: brightness_move_up
  id: long_down
- platform: mqtt
  topic: '{{ z2m_base_topic ~ ''/'' ~ z2m_controller ~ ''/action'' }}'
  payload: brightness_stop
  id: stop
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id: 'off'
    sequence: !input double
  - conditions:
    - condition: trigger
      id: 'on'
    sequence: !input single
  - conditions:
    - condition: trigger
      id: long_down
    sequence: !input long
  - conditions:
    - condition: trigger
      id: stop
    sequence: !input released
