blueprint:
  name: Ikea on/off button (E1743) and IKEA Rodret (E2201) cover control 
  description: Control cover with IKEA Tradfri ON/OFF button (E1743) or IKEA Rodret (E2201). 
  domain: automation
  input:
    button:
      name: button
      description: Ikea ON/OFF Button (E1743) or IKEA Rodret (E2201)
      selector:
        device:
          filter:
          - integration: mqtt
            manufacturer: IKEA
            model: RODRET wireless dimmer/power switch (E2201)
          - integration: mqtt
            manufacturer: IKEA
            model: TRADFRI on/off switch (E1743)
          multiple: false
    cover:
      name: Cover
      description: Controlled Cover
      selector:
        target:
          entity:
          - domain:
            - cover
  source_url: https://github.com/Citrowallon/blueprints-HA/blob/main/ikea-on-off-button-e1743-to-control-covers-blinds.yaml
mode: restart
max_exceeded: silent
trigger:
- trigger: device
  domain: mqtt
  device_id: !input button
  type: action
  subtype: 'off'
  id: 'off'
- trigger: device
  domain: mqtt
  device_id: !input button
  type: action
  subtype: 'on'
  id: 'on'
- trigger: device
  domain: mqtt
  device_id: !input button
  type: action
  subtype: brightness_move_up
  id: move_up
- trigger: device
  domain: mqtt
  device_id: !input button
  type: action
  subtype: brightness_move_down
  id: move_down
- trigger: device
  domain: mqtt
  device_id: !input button
  type: action
  subtype: brightness_stop
  id: stop
action:
- choose:
  - conditions:
    - condition: trigger
      id: 'off'
    sequence:
    - service: cover.close_cover
      target: !input cover
      data: {}
  - conditions:
    - condition: trigger
      id: 'on'
    sequence:
    - service: cover.open_cover
      data: {}
      target: !input cover
  - conditions:
    - condition: trigger
      id: 'move_down'
    sequence:
    - service: cover.close_cover
      data: {}
      target: !input cover
  - conditions:
    - condition: trigger
      id: 'move_up'
    sequence:
    - service: cover.open_cover
      data: {}
      target: !input cover
  - conditions:
    - condition: trigger
      id: 'stop'
    sequence:
    - service: cover.stop_cover
      data: {}
      target: !input cover
